//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechRecognitionWebApp.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        public int ImgesId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ImagePath { get; set; }
    
        public virtual UsersInfo UsersInfo { get; set; }
    }
}
